# Generated by Django 5.2.11 on 2026-02-28 02:04

import common.utils
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalEventOutbox",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=common.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("aggregate_type", models.CharField(max_length=100)),
                ("aggregate_id", models.CharField(max_length=100)),
                ("event_type", models.CharField(max_length=100)),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("next_attempt_at", models.DateTimeField(null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "portal event outbox",
                "verbose_name_plural": "portal event outbox entries",
                "db_table": "portal_event_outbox",
                "ordering": ["-created_at"],
            },
        ),
        # Table renames must come before index renames so Django's state
        # machine resolves the correct table name for index operations.
        migrations.AlterModelTable(
            name="uploadbatch",
            table="portal_upload_batch",
        ),
        migrations.AlterModelTable(
            name="uploadfile",
            table="portal_upload_file",
        ),
        migrations.AlterModelTable(
            name="uploadpart",
            table="portal_upload_part",
        ),
        migrations.AlterModelTable(
            name="uploadsession",
            table="portal_upload_session",
        ),
        migrations.RenameIndex(
            model_name="uploadfile",
            new_name="portal_uplo_uploade_0016ce_idx",
            old_name="upload_file_uploade_4deeb7_idx",
        ),
        migrations.RenameIndex(
            model_name="uploadfile",
            new_name="portal_uplo_status_e50e20_idx",
            old_name="upload_file_status_d3e036_idx",
        ),
        migrations.AlterField(
            model_name="uploadfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploading", "Uploading"),
                    ("stored", "Stored"),
                    ("failed", "Failed"),
                ],
                default="uploading",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="portaleventoutbox",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["next_attempt_at"],
                name="idx_portal_outbox_pending_next",
            ),
        ),
        migrations.AddConstraint(
            model_name="portaleventoutbox",
            constraint=models.UniqueConstraint(
                fields=("event_type", "idempotency_key"),
                name="unique_portal_event_type_idempotency_key",
            ),
        ),
    ]
