#!/usr/bin/env python
"""doorito -- CLI for the Doorito project."""

import os
import sys

from dotenv import load_dotenv

load_dotenv()

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "boot.settings")
os.environ.setdefault("DJANGO_CONFIGURATION", "Dev")

import configurations  # noqa: E402

configurations.setup()

import click  # noqa: E402


@click.group()
@click.version_option(version="0.1.0", prog_name="doorito")
def cli():
    """Doorito project CLI."""
    pass


@cli.command()
def hello():
    """Say hello (example command)."""
    click.echo("Hello from Doorito!")


@cli.command()
def check():
    """Run Django system checks."""
    from django.core.management import call_command

    call_command("check")


if __name__ == "__main__":
    cli()
