# Generated by Django 5.2.11 on 2026-02-26 23:53

import django.core.serializers.json
from django.db import migrations, models

import common.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=common.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("aggregate_type", models.CharField(max_length=100)),
                ("aggregate_id", models.CharField(max_length=100)),
                ("event_type", models.CharField(max_length=100)),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("next_attempt_at", models.DateTimeField(null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "outbox event",
                "verbose_name_plural": "outbox events",
                "db_table": "outbox_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "pending")),
                        fields=["next_attempt_at"],
                        name="idx_outbox_pending_next",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_type", "idempotency_key"),
                        name="unique_event_type_idempotency_key",
                    )
                ],
            },
        ),
    ]
