# Generated by Django 5.2.11 on 2026-02-27 15:45

import django.core.serializers.json
from django.db import migrations, models

import common.utils


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=common.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Target URL to POST events to", max_length=2048
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Shared secret for HMAC-SHA256 request signing",
                        max_length=255,
                    ),
                ),
                (
                    "event_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text='JSON list of event types to subscribe to (e.g., ["file.stored"]). Empty list matches all events.',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable or disable delivery to this endpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "webhook endpoint",
                "verbose_name_plural": "webhook endpoints",
                "db_table": "webhook_endpoint",
                "ordering": ["-created_at"],
            },
        ),
    ]
