# Generated by Django 5.2.11 on 2026-02-25 22:56

import common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=common.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("init", "Init"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="init",
                        max_length=20,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "upload batch",
                "verbose_name_plural": "upload batches",
                "db_table": "upload_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=common.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(help_text="File size in bytes"),
                ),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("stored", "Stored"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="uploads.uploadbatch",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "upload file",
                "verbose_name_plural": "upload files",
                "db_table": "upload_file",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=common.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("init", "Init"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("aborted", "Aborted"),
                        ],
                        default="init",
                        max_length=20,
                    ),
                ),
                (
                    "chunk_size_bytes",
                    models.PositiveIntegerField(
                        default=5242880,
                        help_text="Target chunk size in bytes (default 5 MB)",
                    ),
                ),
                (
                    "total_size_bytes",
                    models.PositiveBigIntegerField(
                        help_text="Total expected file size in bytes"
                    ),
                ),
                (
                    "total_parts",
                    models.PositiveIntegerField(
                        help_text="Total expected number of parts"
                    ),
                ),
                ("bytes_received", models.PositiveBigIntegerField(default=0)),
                ("completed_parts", models.PositiveIntegerField(default=0)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "upload_token",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="uploads.uploadfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "upload session",
                "verbose_name_plural": "upload sessions",
                "db_table": "upload_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadPart",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=common.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "part_number",
                    models.PositiveIntegerField(help_text="1-indexed chunk ordinal"),
                ),
                (
                    "offset_bytes",
                    models.PositiveBigIntegerField(
                        help_text="Byte offset of this part"
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        help_text="Size of this part in bytes"
                    ),
                ),
                ("sha256", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("received", "Received"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "temp_storage_key",
                    models.CharField(
                        blank=True,
                        help_text="Temporary storage location for chunk before assembly",
                        max_length=500,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="uploads.uploadsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "upload part",
                "verbose_name_plural": "upload parts",
                "db_table": "upload_part",
                "ordering": ["part_number"],
            },
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(
                fields=["uploaded_by", "-created_at"],
                name="upload_file_uploade_4deeb7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["status"], name="upload_file_status_d3e036_idx"),
        ),
        migrations.AddConstraint(
            model_name="uploadpart",
            constraint=models.UniqueConstraint(
                fields=("session", "part_number"), name="unique_session_part_number"
            ),
        ),
    ]
